# Generated by Django 3.2.16 on 2024-09-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20240913_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
