# Generated by Django 3.2.16 on 2024-09-19 16:39

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_group'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user__ne', django.db.models.expressions.F('following'))), name='self_follow'),
        ),
    ]
