# Generated by Django 3.2.16 on 2024-09-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_follow_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='self_follow',
        ),
    ]
